### ISSUE TITLE
New command: report_reference for FPGA fabric modeling

### ISSUE THREAD

**Issue by tangxifan** [lnis-uofu/OpenFPGA#1780]
**Is your feature request related to a problem? Please describe.**
During architecture exploration, the number of repeatable tiles or routing blocks are critical to make decisions from a physical design perspective. However, currently, the number of repeatable tiles and the number of instances for each unique tiles can only be inferred from the auto-generated netlists. This requires additional effort from eye checks or scripting. 

It is fairly reasonable to create a new command in the OpenFPGA shell: ``report_reference``
It can report the number of instances for each unique module, under a given module. This is similar to the ``report_reference`` of other EDA tools, e.g., Synopsys Design Compiler.

**Describe the solution you'd like**

The new command ``report_reference`` will have the following options

- ``--file <string>`` specify the file to output results
- ``--module <string>`` specify the module name, under which the references of child modules will be reported. The module name should be valid name. Otherwise, errors will be thrown.
- ``--no_time_stamp`` remove the time stamp from output file
- ``--verbose`` turn on verbose log

The results will look like in the log:

```
Reference        Count   
-----------------------------------------------------------------------------
cbx_1__cb_mux_size6                2     
cbx_1__cb_mux_size8               3    
cbx_1__config_group_mem_size30    1 
-----------------------------------------------------------------------------
Total 3 references
```

The resulting file (specified through the ``--file`` option) will follow a YAML format:

```
references:
- module: cbx_1__cb_mux_size6 
  count: 2
  instances:
    - mux_ipin_0
    - mux_ipin_1
- module: cbx_1__cb_mux_size6 
  count: 3
  instances:
    - mux_ipin_3
    - mux_ipin_4
    - mux_ipin_6
- module: cbx_1__config_group_mem_size30
  count: 1
  instances:
    - cbx_1__config_group_mem_size30
```
