### ISSUE TITLE
Cancel Previous CI runs once there is an update on a pull request

### ISSUE THREAD

**Issue by tangxifan** [lnis-uofu/OpenFPGA#398]
**Is your feature request related to a problem? Please describe.**
Currently, our CI may be jammed if there are many commits pushed on a pull request.
Think about there are 10 commits pushed to a pull request in 5 minutes.

**Describe the solution you'd like**
In our workflow, we should be able to cancel previous runs.
For example

```
   - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
```
